server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri:
          lb://USER-SERVICE
        predicates:
        - Path=/apiuser/**
      - id: FAVOURITE-SERVICE
        uri:
          lb://FAVOURITE-SERVICE
        predicates:
        - Path=/api/**
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone : http://localhost:8761/eureka/
  instance:
    hostname: localhost